import { z } from 'zod';

// =============================================================================
// Task Types - What kind of work needs to be done
// =============================================================================

export const TaskTypeSchema = z.enum([
  // Crop management
  'plant',      // Put a plant in the ground
  'sow',        // Direct seed into soil
  'thin',       // Remove excess seedlings
  'prune',      // Cut back growth
  'deadhead',   // Remove spent flowers
  'hill',       // Mound soil around stems (potato)
  'harvest',    // Collect ripe produce
  'water',      // Irrigate
  'weed',       // Remove weeds
  'stake',      // Add support structure
  'inspect',    // Observe and record state
  'mulch',      // Add mulch layer
  'fertilize',  // Apply nutrients
  'amend',      // Apply soil amendment (changes conditions)
  'net',        // Install/manage bird netting
  'trap',       // Set/check live traps or snap traps

  // Infrastructure & logistics
  'build',      // Construct/install infrastructure (fence, trellis, beds)
  'procure',    // Acquire materials or supplies
  'prepare',    // Prep work (soil blocks, seed cutting, bed prep)
]);

export type TaskType = z.infer<typeof TaskTypeSchema>;

// =============================================================================
// Task Target - Where the work needs to happen
// =============================================================================

export const TaskTargetSchema = z.discriminatedUnion('target_type', [
  // Target a specific plant
  z.object({
    target_type: z.literal('plant'),
    plant_id: z.string(),
  }),
  // Target a specific subcell (for planting, weeding)
  z.object({
    target_type: z.literal('subcell'),
    subcell_id: z.string(),
  }),
  // Target a zone (batch operations)
  z.object({
    target_type: z.literal('zone'),
    zone_x: z.number().int().min(0),
    zone_y: z.number().int().min(0),
  }),
  // Target arbitrary position (for navigation)
  z.object({
    target_type: z.literal('position'),
    x_in: z.number(),
    y_in: z.number(),
  }),
  // Target a named infrastructure element (fence, trellis, channel)
  z.object({
    target_type: z.literal('infrastructure'),
    infrastructure_id: z.string(),
  }),
  // Target the entire garden (garden-level tasks: fence walk, mowing, cleanup)
  z.object({
    target_type: z.literal('garden'),
  }),
]);

export type TaskTarget = z.infer<typeof TaskTargetSchema>;

// =============================================================================
// Task Assignment - Who will do the work
// =============================================================================

export const TaskAssignmentSchema = z.discriminatedUnion('executor_type', [
  z.object({
    executor_type: z.literal('robot'),
    robot_id: z.string(),
  }),
  z.object({
    executor_type: z.literal('human'),
    user_id: z.string(),
    user_name: z.string().optional(),
  }),
  z.object({
    executor_type: z.literal('unassigned'),
  }),
]);

export type TaskAssignment = z.infer<typeof TaskAssignmentSchema>;

// =============================================================================
// Task Status
// =============================================================================

export const TaskStatusSchema = z.enum([
  'queued',       // Waiting to be assigned
  'assigned',     // Assigned but not started
  'in_progress',  // Currently being executed
  'completed',    // Successfully finished
  'failed',       // Attempted but failed
  'cancelled',    // Cancelled before completion
]);

export type TaskStatus = z.infer<typeof TaskStatusSchema>;

// =============================================================================
// Labor Type - Who CAN do this work
// =============================================================================

export const LaborTypeSchema = z.enum([
  'manual',   // Human only (complex judgment required)
  'robot',    // Robot only (dangerous or repetitive)
  'either',   // Either can do it
]);

export type LaborType = z.infer<typeof LaborTypeSchema>;

// =============================================================================
// Task - Unified work directive for humans and robots
// =============================================================================

/**
 * Task - A concrete work directive
 *
 * Generated by the operational planner from rules comparing current vs expected state.
 * Can be assigned to either a human or robot executor.
 * Execution creates an Episode record.
 */
export const TaskSchema = z.object({
  task_id: z.string(),
  type: TaskTypeSchema,

  // Where
  target: TaskTargetSchema,

  // Task-specific parameters
  parameters: z.record(z.any()).optional(), // e.g., {cut_height_cm: 15, remove_fruit: true}

  // Scheduling
  created_at: z.string(),                   // ISO datetime
  priority: z.number().int().min(1).max(10), // 10 = urgent, 1 = whenever
  due_by: z.string().optional(),            // ISO datetime

  // Assignment
  assigned_to: TaskAssignmentSchema.optional(),
  assigned_at: z.string().optional(),       // ISO datetime

  // Required capabilities (for robot matching)
  required_capabilities: z.array(z.string()).optional(), // e.g., ['cutting', 'gripping']

  // Labor classification
  labor_type: LaborTypeSchema.optional(),
  estimated_duration_minutes: z.number().min(0).optional(),
  actual_duration_minutes: z.number().min(0).optional(),

  // Status tracking
  status: TaskStatusSchema,
  started_at: z.string().optional(),        // ISO datetime
  completed_at: z.string().optional(),      // ISO datetime

  // Outcome
  success: z.boolean().optional(),
  failure_reason: z.string().optional(),

  // Linkage
  episode_id: z.string().optional(),        // Execution record
  observations_ids: z.array(z.string()).optional(), // Observations from this task

  // Provenance
  generated_by_rule: z.string().optional(), // Which rule created this task
  garden_state_id: z.string().optional(),   // State that triggered this task
});

export type Task = z.infer<typeof TaskSchema>;

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Create a new Task ID
 */
export function createTaskId(type: TaskType): string {
  return `task_${type}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

/**
 * Check if task is actionable (can be worked on)
 */
export function isTaskActionable(task: Task): boolean {
  return task.status === 'queued' || task.status === 'assigned';
}

/**
 * Check if task is terminal (won't change status)
 */
export function isTaskTerminal(task: Task): boolean {
  return task.status === 'completed' || task.status === 'failed' || task.status === 'cancelled';
}

/**
 * Check if a duplicate task exists
 */
export function isDuplicateTask(
  newTask: Pick<Task, 'type' | 'target'>,
  existingTasks: Task[]
): boolean {
  return existingTasks.some(existing => {
    if (existing.type !== newTask.type) return false;
    if (isTaskTerminal(existing)) return false;

    // Compare targets
    if (newTask.target.target_type !== existing.target.target_type) return false;

    switch (newTask.target.target_type) {
      case 'plant':
        return (existing.target as { target_type: 'plant'; plant_id: string }).plant_id ===
               (newTask.target as { target_type: 'plant'; plant_id: string }).plant_id;
      case 'subcell':
        return (existing.target as { target_type: 'subcell'; subcell_id: string }).subcell_id ===
               (newTask.target as { target_type: 'subcell'; subcell_id: string }).subcell_id;
      case 'zone':
        const existingZone = existing.target as { target_type: 'zone'; zone_x: number; zone_y: number };
        const newZone = newTask.target as { target_type: 'zone'; zone_x: number; zone_y: number };
        return existingZone.zone_x === newZone.zone_x && existingZone.zone_y === newZone.zone_y;
      default:
        return false;
    }
  });
}

/**
 * Check if task is in cooldown period
 */
export function isTaskInCooldown(
  taskType: TaskType,
  targetId: string,
  completedTasks: Task[],
  cooldownDays: number = 7
): boolean {
  const cooldownMs = cooldownDays * 24 * 60 * 60 * 1000;
  const now = Date.now();

  return completedTasks.some(task => {
    if (task.type !== taskType) return false;
    if (task.status !== 'completed') return false;
    if (!task.completed_at) return false;

    const completedTime = new Date(task.completed_at).getTime();
    if (now - completedTime > cooldownMs) return false;

    // Check target match
    switch (task.target.target_type) {
      case 'plant':
        return task.target.plant_id === targetId;
      case 'subcell':
        return task.target.subcell_id === targetId;
      default:
        return false;
    }
  });
}

/**
 * Sort tasks by priority and due date
 */
export function sortTasksByPriority(tasks: Task[]): Task[] {
  return [...tasks].sort((a, b) => {
    // Higher priority first
    if (a.priority !== b.priority) {
      return b.priority - a.priority;
    }
    // Earlier due date first
    if (a.due_by && b.due_by) {
      return new Date(a.due_by).getTime() - new Date(b.due_by).getTime();
    }
    if (a.due_by) return -1;
    if (b.due_by) return 1;
    // Earlier creation first
    return new Date(a.created_at).getTime() - new Date(b.created_at).getTime();
  });
}

/**
 * Filter tasks by executor capability
 */
export function filterTasksForRobot(
  tasks: Task[],
  robotCapabilities: string[]
): Task[] {
  return tasks.filter(task => {
    if (!task.required_capabilities) return true;
    return task.required_capabilities.every(cap => robotCapabilities.includes(cap));
  });
}
