export { tickPlant, tickDay } from './tickDay';
export type { TickResult, DayResult } from './tickDay';
export { simulateGrowth, harvestPlant, collectSnapshots, simulateFromState, simulateWithTasks } from './simulate';
export type { HarvestPolicy, SimulationResult, DaySnapshot, SimulationContext, SuccessionConfig } from './simulate';
export { initPlantStates } from './initPlantStates';
export { evaluateTrigger } from './evaluateTrigger';
export { generateTasksFromLifecycle } from './generateTasksFromLifecycle';
export { generateTasksFromRules } from './generateTasksFromRules';
export { evaluateRule, buildConditionsContext } from './evaluateRule';
export type { RuleContext } from './evaluateRule';
export { planDay } from './operationalPlanner';
export type { PlannerInput, PlannerResult } from './operationalPlanner';
export { adaptSeasonTasks } from './adaptSeasonTasks';
export { resolveTask } from './resolveTask';
export type { ResolutionResult, ConditionOverride } from './resolveTask';
export { computeOverrideValue } from './simulate';
