/**
 * Task Calendar — weekly stacked bar chart of task-derived labor.
 *
 * Consumes DaySnapshot[] from simulation (tasks generated by operationalPlanner).
 * Stacked by task type, Y-axis is minutes/week. Click bar for day detail.
 */

import React, { useMemo, useState, useCallback } from 'react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
  ReferenceLine,
} from 'recharts';
import type { DaySnapshot } from '@core/engine/simulate';
import type { Task } from '@core/types/Task';

const TASK_TYPES_DISPLAY = [
  'harvest', 'water', 'plant', 'thin', 'prune', 'hill',
  'weed', 'inspect', 'mulch', 'fertilize', 'sow', 'build', 'prepare',
] as const;

const TASK_TYPE_COLORS: Record<string, string> = {
  harvest: '#22c55e',
  water: '#3b82f6',
  plant: '#10b981',
  thin: '#a78bfa',
  prune: '#f59e0b',
  hill: '#d97706',
  weed: '#84cc16',
  inspect: '#6b7280',
  mulch: '#92400e',
  fertilize: '#8b5cf6',
  sow: '#14b8a6',
  build: '#f97316',
  prepare: '#64748b',
};

interface WeekRow {
  weekLabel: string;
  weekStart: Date;
  totalMinutes: number;
  taskCount: number;
  tasks: Task[];
  minutesByType: Record<string, number>;
}

function formatWeekLabel(date: Date): string {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[date.getMonth()]} ${date.getDate()}`;
}

/** Minutes per lb to harvest + rinse + store. Greens take longer than roots/fruit. */
const HARVEST_MINUTES_PER_LB: Record<string, number> = {
  lettuce_bss: 4,
  spinach_bloomsdale: 4,
  kale_red_russian: 3,
  tomato_sun_gold: 2,
  tomato_amish_paste: 1.5,
  potato_kennebec: 1,
  corn_nothstine_dent: 1,
};
const DEFAULT_HARVEST_MIN_PER_LB = 2;

/** Estimate weekly harvest labor from harvestable inventory on a single snapshot. */
function estimateHarvestMinutes(snap: DaySnapshot): number {
  let totalMinutes = 0;
  for (const plant of snap.plants) {
    if (!plant.is_harvestable || plant.accumulated_lbs <= 0.01) continue;
    if (plant.lifecycle === 'dead' || plant.lifecycle === 'pulled') continue;
    const rate = HARVEST_MINUTES_PER_LB[plant.species_id] ?? DEFAULT_HARVEST_MIN_PER_LB;
    totalMinutes += plant.accumulated_lbs * rate;
  }
  return totalMinutes;
}

function buildWeeklyData(snapshots: DaySnapshot[], orderTasks?: Task[]): WeekRow[] {
  if (snapshots.length === 0) return [];

  const weekMap = new Map<string, WeekRow>();

  // Helper: ensure a week row exists
  function ensureWeek(date: Date): WeekRow {
    const dayOfWeek = date.getDay();
    const monday = new Date(date);
    monday.setDate(date.getDate() - ((dayOfWeek + 6) % 7));
    const weekKey = monday.toISOString().slice(0, 10);

    if (!weekMap.has(weekKey)) {
      const minutesByType: Record<string, number> = {};
      for (const type of TASK_TYPES_DISPLAY) {
        minutesByType[type] = 0;
      }
      weekMap.set(weekKey, {
        weekLabel: formatWeekLabel(monday),
        weekStart: monday,
        totalMinutes: 0,
        taskCount: 0,
        tasks: [],
        minutesByType,
      });
    }
    return weekMap.get(weekKey)!;
  }

  // Track which weeks already got harvest estimate (sample once per week)
  const harvestEstimateWeeks = new Set<string>();

  for (const snap of snapshots) {
    const d = new Date(snap.date);
    const row = ensureWeek(d);
    const weekKey = row.weekStart.toISOString().slice(0, 10);

    // Add real tasks from simulation
    const tasks = snap.tasks ?? [];
    for (const task of tasks) {
      const minutes = task.estimated_duration_minutes ?? 0;
      row.totalMinutes += minutes;
      row.taskCount++;
      row.tasks.push(task);
      row.minutesByType[task.type] = (row.minutesByType[task.type] ?? 0) + minutes;
    }

    // Sample projected harvest labor once per week (mid-week snapshot)
    if (d.getDay() === 3 && !harvestEstimateWeeks.has(weekKey)) {
      harvestEstimateWeeks.add(weekKey);
      const harvestMinutes = estimateHarvestMinutes(snap);
      if (harvestMinutes > 0) {
        row.totalMinutes += harvestMinutes;
        row.minutesByType['harvest'] = (row.minutesByType['harvest'] ?? 0) + harvestMinutes;
      }
    }
  }

  // Merge order-driven tasks by due_by date
  if (orderTasks?.length) {
    for (const task of orderTasks) {
      const dueDate = task.due_by ? new Date(task.due_by) : new Date(task.created_at);
      const row = ensureWeek(dueDate);
      const minutes = task.estimated_duration_minutes ?? 0;
      row.totalMinutes += minutes;
      row.taskCount++;
      row.tasks.push(task);
      row.minutesByType[task.type] = (row.minutesByType[task.type] ?? 0) + minutes;
    }
  }

  // Remove empty weeks (no tasks and no harvest estimate)
  for (const [key, row] of weekMap) {
    if (row.totalMinutes === 0 && row.taskCount === 0) weekMap.delete(key);
  }

  return Array.from(weekMap.values()).sort(
    (a, b) => a.weekStart.getTime() - b.weekStart.getTime(),
  );
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function TaskTooltip({ active, payload, label }: any) {
  if (!active || !payload?.length) return null;
  const row: WeekRow = payload[0]?.payload;
  if (!row) return null;

  const activeTypes = TASK_TYPES_DISPLAY.filter(t => (row.minutesByType[t] ?? 0) > 0);

  return (
    <div style={{
      backgroundColor: '#1f2937', border: '1px solid #374151',
      borderRadius: 4, padding: '8px 12px', fontSize: 12, maxWidth: 280,
    }}>
      <p style={{ color: '#f3f4f6', margin: '0 0 6px', fontWeight: 600 }}>
        {label} — {row.taskCount} tasks
      </p>
      <p style={{ color: '#d1d5db', margin: '0 0 4px' }}>
        Total: {Math.round(row.totalMinutes)} min ({Math.round(row.totalMinutes / 7)} min/day)
      </p>
      {activeTypes.map(t => (
        <p key={t} style={{ color: TASK_TYPE_COLORS[t], margin: '2px 0' }}>
          {t}: {Math.round(row.minutesByType[t]!)} min
        </p>
      ))}
    </div>
  );
}

const BUDGET_LOW_MIN = 20 * 7;   // 140 min/week
const BUDGET_HIGH_MIN = 30 * 7;  // 210 min/week

// ── Task Detail Panel ─────────────────────────────────────────────────────

interface StepDisplay {
  name: string;
  scale: string;
  minutes: number;
  count: number;
  total: number;
  instructions?: string;
}

function TaskDetail({ task, onBack }: { task: Task; onBack: () => void }) {
  const params = task.parameters ?? {};
  const steps = (params.steps as StepDisplay[] | undefined) ?? [];
  return (
    <div className="space-y-2">
      <button onClick={onBack} className="text-xs text-gray-500 hover:text-gray-300">
        &larr; back to list
      </button>
      <div className="flex items-center gap-2">
        <span
          className="w-3 h-3 rounded-sm"
          style={{ backgroundColor: TASK_TYPE_COLORS[task.type] ?? '#6b7280' }}
        />
        <h4 className="text-sm font-semibold text-white capitalize">{task.type}</h4>
        <span className="text-xs text-gray-500">P{task.priority}</span>
      </div>

      {params.species_name && (
        <div className="text-xs text-gray-300">
          {params.species_name}
          {params.plant_count ? ` (${params.plant_count} plants` : ''}
          {params.row_count ? `, ${params.row_count} rows)` : params.plant_count ? ')' : ''}
        </div>
      )}
      {params.activity_name && (
        <div className="text-xs text-gray-400">{params.activity_name}</div>
      )}
      {task.estimated_duration_minutes != null && (
        <div className="text-xs text-gray-400">
          Total: <span className="text-gray-200 font-mono">{Math.round(task.estimated_duration_minutes)} min</span>
        </div>
      )}

      {steps.length > 0 && (
        <div className="space-y-1 mt-1">
          <div className="text-[10px] text-gray-500 uppercase tracking-wider">Steps</div>
          {steps.map((step, i) => (
            <div key={i} className="bg-gray-800/50 rounded px-2 py-1">
              <div className="flex items-center justify-between text-xs">
                <span className="text-gray-200">{step.name}</span>
                <span className="text-gray-400 font-mono shrink-0 ml-2">
                  {step.total >= 1 ? `${step.total.toFixed(1)} min` : `${(step.total * 60).toFixed(0)}s`}
                </span>
              </div>
              <div className="text-[10px] text-gray-500">
                {step.scale === 'plant' && `${(step.minutes * 60).toFixed(0)}s × ${step.count} plants`}
                {step.scale === 'row' && `${step.minutes} min × ${step.count} row${step.count > 1 ? 's' : ''}`}
                {step.scale === 'fixed' && `${step.minutes} min (setup)`}
              </div>
              {step.instructions && (
                <div className="text-[10px] text-gray-500 mt-0.5 italic">{step.instructions}</div>
              )}
            </div>
          ))}
        </div>
      )}

      {params.equipment && (params.equipment as string[]).length > 0 && (
        <div className="text-xs mt-1">
          <span className="text-gray-500">Equipment: </span>
          <span className="text-gray-300">{(params.equipment as string[]).join(', ')}</span>
        </div>
      )}
      {task.generated_by_rule && (
        <div className="text-[10px] text-gray-600 mt-1">
          Source: {task.generated_by_rule}
        </div>
      )}
    </div>
  );
}

// ── Task List (grouped by type within a week) ─────────────────────────────

interface TaskGroupRow {
  type: string;
  count: number;
  totalMinutes: number;
  tasks: Task[];
}

function groupForDisplay(tasks: Task[]): TaskGroupRow[] {
  const map = new Map<string, TaskGroupRow>();
  for (const task of tasks) {
    const entry = map.get(task.type) ?? { type: task.type, count: 0, totalMinutes: 0, tasks: [] };
    entry.count++;
    entry.totalMinutes += task.estimated_duration_minutes ?? 0;
    entry.tasks.push(task);
    map.set(task.type, entry);
  }
  return Array.from(map.values()).sort((a, b) => b.totalMinutes - a.totalMinutes);
}

function TaskModal({ row, onClose }: { row: WeekRow; onClose: () => void }) {
  const groups = useMemo(() => groupForDisplay(row.tasks), [row.tasks]);
  const [detailTask, setDetailTask] = useState<Task | null>(null);

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60"
      onClick={onClose}
    >
      <div
        className="bg-gray-900 border border-gray-700 rounded-lg shadow-2xl w-[90vw] max-w-2xl max-h-[80vh] flex flex-col"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-gray-700">
          <div>
            <h3 className="text-sm font-semibold text-white">
              {row.weekLabel} — {row.taskCount} tasks
            </h3>
            <div className="text-xs text-gray-400">
              {Math.round(row.totalMinutes)} min total ({Math.round(row.totalMinutes / 7)} min/day)
            </div>
          </div>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-300 text-lg px-2">&times;</button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-4 py-3">
          {detailTask ? (
            <TaskDetail task={detailTask} onBack={() => setDetailTask(null)} />
          ) : (
            <div className="grid gap-2">
              {groups.map(group => {
                const species = group.tasks[0]?.parameters?.species_name as string | undefined;
                const duration = group.totalMinutes >= 60
                  ? `${(group.totalMinutes / 60).toFixed(1)} hrs`
                  : `${Math.round(group.totalMinutes)} min`;
                return (
                  <button
                    key={group.type}
                    onClick={() => setDetailTask(group.tasks[0]!)}
                    className="grid grid-cols-[auto_1fr_auto] items-center gap-x-3 py-2.5 px-4 rounded-lg bg-gray-800 hover:bg-gray-750 text-sm text-left w-full transition-colors"
                  >
                    <span
                      className="w-2.5 h-2.5 rounded-full"
                      style={{ backgroundColor: TASK_TYPE_COLORS[group.type] ?? '#6b7280' }}
                    />
                    <div className="min-w-0">
                      <span className="text-white capitalize">{group.type}</span>
                      {species && (
                        <span className="text-gray-500 ml-2 text-xs">{species}</span>
                      )}
                    </div>
                    <div className="flex items-center gap-3 shrink-0 text-xs">
                      <span className="text-gray-400 font-mono">{group.count}x</span>
                      <span className="text-gray-300 font-mono w-16 text-right">{duration}</span>
                      <span className="text-gray-600">&rsaquo;</span>
                    </div>
                  </button>
                );
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────

interface TaskTimelineProps {
  snapshots: DaySnapshot[];
  orderTasks?: Task[];
}

export function TaskTimeline({ snapshots, orderTasks }: TaskTimelineProps) {
  const weekRows = useMemo(() => buildWeeklyData(snapshots, orderTasks), [snapshots, orderTasks]);
  // Flatten minutesByType into top-level keys for Recharts dataKey access
  const chartData = useMemo(() => weekRows.map(row => ({
    ...row,
    ...row.minutesByType,
  })), [weekRows]);
  const [selectedWeek, setSelectedWeek] = useState<string | null>(null);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleBarClick = useCallback((data: any) => {
    if (data?.activeLabel) {
      setSelectedWeek(prev => prev === data.activeLabel ? null : data.activeLabel);
    }
  }, []);

  if (chartData.length === 0) {
    return (
      <div className="bg-gray-900 p-4">
        <p className="text-gray-400 text-xs">No task data — simulation may not include task generation</p>
      </div>
    );
  }

  const totalMinutes = chartData.reduce((s, r) => s + r.totalMinutes, 0);
  const peakWeek = chartData.reduce((max, r) => r.totalMinutes > max.totalMinutes ? r : max, chartData[0]!);
  const avgMinPerWeek = totalMinutes / chartData.length;
  const overBudgetWeeks = chartData.filter(r => r.totalMinutes > BUDGET_HIGH_MIN).length;

  const activeTypes = TASK_TYPES_DISPLAY.filter(
    t => weekRows.some(row => (row.minutesByType[t] ?? 0) > 0),
  );

  const selectedRow = selectedWeek ? weekRows.find(r => r.weekLabel === selectedWeek) : null;

  return (
    <div className="bg-gray-900 p-4 h-full flex flex-col">
      <div className="flex flex-wrap gap-x-6 gap-y-1 mb-3 text-xs text-gray-400">
        <span>Peak: <strong className="text-white">{Math.round(peakWeek.totalMinutes)} min</strong> ({peakWeek.weekLabel})</span>
        <span>Avg: <strong className="text-white">{Math.round(avgMinPerWeek)} min/wk</strong> ({Math.round(avgMinPerWeek / 7)} min/day)</span>
        <span>Season: <strong className="text-white">{Math.round(totalMinutes / 60)} hrs</strong></span>
        <span>Over budget: <strong className={overBudgetWeeks > 0 ? 'text-red-400' : 'text-emerald-400'}>
          {overBudgetWeeks} weeks
        </strong></span>
        <span>Budget: <strong className="text-emerald-400">20-30 min/day</strong></span>
      </div>

      <div className="flex-1 min-h-0">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart
            data={chartData}
            margin={{ top: 10, right: 20, left: 0, bottom: 5 }}
            onClick={handleBarClick}
            style={{ cursor: 'pointer' }}
          >
            <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
            <XAxis
              dataKey="weekLabel"
              stroke="#9ca3af"
              tick={{ fontSize: 10 }}
              interval={2}
            />
            <YAxis
              stroke="#9ca3af"
              tick={{ fontSize: 10 }}
              label={{
                value: 'min/week',
                angle: -90,
                position: 'insideLeft',
                fontSize: 10,
                fill: '#9ca3af',
                offset: 10,
              }}
            />
            <Tooltip content={<TaskTooltip />} />
            <Legend wrapperStyle={{ fontSize: '10px' }} iconType="square" iconSize={8} />
            <ReferenceLine
              y={BUDGET_HIGH_MIN}
              stroke="#22d3ee"
              strokeDasharray="6 3"
              label={{ value: '30 min/day', fill: '#22d3ee', fontSize: 10, position: 'right' }}
            />
            <ReferenceLine
              y={BUDGET_LOW_MIN}
              stroke="#86efac"
              strokeDasharray="3 3"
              label={{ value: '20 min/day', fill: '#86efac', fontSize: 10, position: 'right' }}
            />
            {activeTypes.map(type => (
              <Bar
                key={type}
                dataKey={type}
                stackId="1"
                fill={TASK_TYPE_COLORS[type] ?? '#6b7280'}
                name={type}
              />
            ))}
          </BarChart>
        </ResponsiveContainer>
      </div>

      {selectedRow && (
        <TaskModal row={selectedRow} onClose={() => setSelectedWeek(null)} />
      )}
    </div>
  );
}
