/**
 * Task Calendar — weekly stacked bar chart of task-derived labor.
 *
 * Consumes DaySnapshot[] from simulation (tasks generated by operationalPlanner).
 * Stacked by task type, Y-axis is minutes/week. Click bar for day detail.
 */

import React, { useMemo, useState, useCallback } from 'react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
  ReferenceLine,
} from 'recharts';
import type { DaySnapshot } from '@core/engine/simulate';
import type { Task } from '@core/types/Task';

const TASK_TYPES_DISPLAY = [
  'harvest', 'water', 'plant', 'thin', 'prune', 'hill',
  'weed', 'inspect', 'mulch', 'fertilize', 'sow', 'build', 'prepare',
] as const;

const TASK_TYPE_COLORS: Record<string, string> = {
  harvest: '#22c55e',
  water: '#3b82f6',
  plant: '#10b981',
  thin: '#a78bfa',
  prune: '#f59e0b',
  hill: '#d97706',
  weed: '#84cc16',
  inspect: '#6b7280',
  mulch: '#92400e',
  fertilize: '#8b5cf6',
  sow: '#14b8a6',
  build: '#f97316',
  prepare: '#64748b',
};

interface WeekRow {
  weekLabel: string;
  weekStart: Date;
  totalMinutes: number;
  taskCount: number;
  tasks: Task[];
  minutesByType: Record<string, number>;
}

function formatWeekLabel(date: Date): string {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[date.getMonth()]} ${date.getDate()}`;
}

function buildWeeklyData(snapshots: DaySnapshot[]): WeekRow[] {
  if (snapshots.length === 0) return [];

  const weekMap = new Map<string, WeekRow>();

  for (const snap of snapshots) {
    const tasks = snap.tasks ?? [];
    if (tasks.length === 0) continue;

    // Get Monday of this week
    const d = new Date(snap.date);
    const dayOfWeek = d.getDay();
    const monday = new Date(d);
    monday.setDate(d.getDate() - ((dayOfWeek + 6) % 7));
    const weekKey = monday.toISOString().slice(0, 10);

    if (!weekMap.has(weekKey)) {
      const minutesByType: Record<string, number> = {};
      for (const type of TASK_TYPES_DISPLAY) {
        minutesByType[type] = 0;
      }
      weekMap.set(weekKey, {
        weekLabel: formatWeekLabel(monday),
        weekStart: monday,
        totalMinutes: 0,
        taskCount: 0,
        tasks: [],
        minutesByType,
      });
    }

    const row = weekMap.get(weekKey)!;
    for (const task of tasks) {
      const minutes = task.estimated_duration_minutes ?? 0;
      row.totalMinutes += minutes;
      row.taskCount++;
      row.tasks.push(task);
      row.minutesByType[task.type] = (row.minutesByType[task.type] ?? 0) + minutes;
    }
  }

  return Array.from(weekMap.values()).sort(
    (a, b) => a.weekStart.getTime() - b.weekStart.getTime(),
  );
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function TaskTooltip({ active, payload, label }: any) {
  if (!active || !payload?.length) return null;
  const row: WeekRow = payload[0]?.payload;
  if (!row) return null;

  const activeTypes = TASK_TYPES_DISPLAY.filter(t => (row.minutesByType[t] ?? 0) > 0);

  return (
    <div style={{
      backgroundColor: '#1f2937', border: '1px solid #374151',
      borderRadius: 4, padding: '8px 12px', fontSize: 12, maxWidth: 280,
    }}>
      <p style={{ color: '#f3f4f6', margin: '0 0 6px', fontWeight: 600 }}>
        {label} — {row.taskCount} tasks
      </p>
      <p style={{ color: '#d1d5db', margin: '0 0 4px' }}>
        Total: {row.totalMinutes} min ({(row.totalMinutes / 7).toFixed(0)} min/day)
      </p>
      {activeTypes.map(t => (
        <p key={t} style={{ color: TASK_TYPE_COLORS[t], margin: '2px 0' }}>
          {t}: {row.minutesByType[t]} min
        </p>
      ))}
    </div>
  );
}

const BUDGET_LOW_MIN = 20 * 7;   // 140 min/week
const BUDGET_HIGH_MIN = 30 * 7;  // 210 min/week

// ── Task Detail Panel ─────────────────────────────────────────────────────

function TaskDetail({ task, onBack }: { task: Task; onBack: () => void }) {
  const params = task.parameters ?? {};
  return (
    <div className="space-y-2">
      <button onClick={onBack} className="text-xs text-gray-500 hover:text-gray-300">
        &larr; back to list
      </button>
      <div className="flex items-center gap-2">
        <span
          className="w-3 h-3 rounded-sm"
          style={{ backgroundColor: TASK_TYPE_COLORS[task.type] ?? '#6b7280' }}
        />
        <h4 className="text-sm font-semibold text-white capitalize">{task.type}</h4>
        <span className="text-xs text-gray-500">P{task.priority}</span>
      </div>

      {params.species_name && (
        <div className="text-xs text-gray-300">{params.species_name}</div>
      )}
      {params.activity_name && (
        <div className="text-xs text-gray-400">{params.activity_name}</div>
      )}
      {task.estimated_duration_minutes != null && (
        <div className="text-xs text-gray-400">
          Duration: <span className="text-gray-200 font-mono">{task.estimated_duration_minutes} min</span>
          {params.plant_count && (
            <span className="text-gray-500"> ({params.plant_count} plants)</span>
          )}
        </div>
      )}
      {params.equipment && (params.equipment as string[]).length > 0 && (
        <div className="text-xs">
          <span className="text-gray-500">Equipment: </span>
          <span className="text-gray-300">{(params.equipment as string[]).join(', ')}</span>
        </div>
      )}
      {params.instructions && (
        <div className="text-xs text-gray-400 bg-gray-800/50 p-2 rounded mt-1">
          {params.instructions as string}
        </div>
      )}
      {task.generated_by_rule && (
        <div className="text-[10px] text-gray-600 mt-1">
          Source: {task.generated_by_rule}
        </div>
      )}
    </div>
  );
}

// ── Task List (grouped by type within a week) ─────────────────────────────

interface TaskGroupRow {
  type: string;
  count: number;
  totalMinutes: number;
  tasks: Task[];
}

function groupForDisplay(tasks: Task[]): TaskGroupRow[] {
  const map = new Map<string, TaskGroupRow>();
  for (const task of tasks) {
    const entry = map.get(task.type) ?? { type: task.type, count: 0, totalMinutes: 0, tasks: [] };
    entry.count++;
    entry.totalMinutes += task.estimated_duration_minutes ?? 0;
    entry.tasks.push(task);
    map.set(task.type, entry);
  }
  return Array.from(map.values()).sort((a, b) => b.totalMinutes - a.totalMinutes);
}

function WeekTaskList({ row, onSelectTask }: { row: WeekRow; onSelectTask: (t: Task) => void }) {
  const groups = useMemo(() => groupForDisplay(row.tasks), [row.tasks]);

  return (
    <div className="border-t border-gray-700 pt-3 mt-3">
      <h3 className="text-sm font-semibold text-white mb-2">
        {row.weekLabel} — {row.taskCount} tasks, {row.totalMinutes} min
        <span className="text-gray-500 font-normal ml-2">({(row.totalMinutes / 7).toFixed(0)} min/day)</span>
      </h3>
      <div className="grid gap-1 max-h-48 overflow-y-auto">
        {groups.map(group => (
          <button
            key={group.type}
            onClick={() => onSelectTask(group.tasks[0]!)}
            className="flex items-center gap-2 py-1.5 px-2 rounded bg-gray-800 hover:bg-gray-750 text-xs text-left w-full transition-colors"
          >
            <span
              className="w-2 h-2 rounded-full shrink-0"
              style={{ backgroundColor: TASK_TYPE_COLORS[group.type] ?? '#6b7280' }}
            />
            <span className="text-white flex-1 capitalize">{group.type}</span>
            {group.tasks[0]?.parameters?.species_name && (
              <span className="text-gray-500 truncate max-w-24">
                {group.tasks[0].parameters.species_name as string}
              </span>
            )}
            <span className="text-gray-400 font-mono">{group.count}x</span>
            <span className="text-gray-400 w-16 text-right shrink-0">
              {group.totalMinutes >= 60 ? `${(group.totalMinutes / 60).toFixed(1)} hrs` : `${group.totalMinutes} min`}
            </span>
            <span className="text-gray-600">&rsaquo;</span>
          </button>
        ))}
      </div>
    </div>
  );
}

// ── Main Component ────────────────────────────────────────────────────────

interface TaskTimelineProps {
  snapshots: DaySnapshot[];
}

export function TaskTimeline({ snapshots }: TaskTimelineProps) {
  const weekRows = useMemo(() => buildWeeklyData(snapshots), [snapshots]);
  // Flatten minutesByType into top-level keys for Recharts dataKey access
  const chartData = useMemo(() => weekRows.map(row => ({
    ...row,
    ...row.minutesByType,
  })), [weekRows]);
  const [selectedWeek, setSelectedWeek] = useState<string | null>(null);
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const handleBarClick = useCallback((data: any) => {
    if (data?.activeLabel) {
      setSelectedWeek(prev => {
        setSelectedTask(null);
        return prev === data.activeLabel ? null : data.activeLabel;
      });
    }
  }, []);

  if (chartData.length === 0) {
    return (
      <div className="bg-gray-900 p-4">
        <p className="text-gray-400 text-xs">No task data — simulation may not include task generation</p>
      </div>
    );
  }

  const totalMinutes = chartData.reduce((s, r) => s + r.totalMinutes, 0);
  const peakWeek = chartData.reduce((max, r) => r.totalMinutes > max.totalMinutes ? r : max, chartData[0]!);
  const avgMinPerWeek = totalMinutes / chartData.length;
  const overBudgetWeeks = chartData.filter(r => r.totalMinutes > BUDGET_HIGH_MIN).length;

  const activeTypes = TASK_TYPES_DISPLAY.filter(
    t => weekRows.some(row => (row.minutesByType[t] ?? 0) > 0),
  );

  const selectedRow = selectedWeek ? chartData.find(r => r.weekLabel === selectedWeek) : null;
  const hasDetail = selectedRow || selectedTask;

  return (
    <div className="bg-gray-900 p-4 h-full flex flex-col">
      <div className="flex flex-wrap gap-x-6 gap-y-1 mb-3 text-xs text-gray-400">
        <span>Peak: <strong className="text-white">{peakWeek.totalMinutes} min</strong> ({peakWeek.weekLabel})</span>
        <span>Avg: <strong className="text-white">{avgMinPerWeek.toFixed(0)} min/wk</strong> ({(avgMinPerWeek / 7).toFixed(0)} min/day)</span>
        <span>Season: <strong className="text-white">{(totalMinutes / 60).toFixed(0)} hrs</strong></span>
        <span>Over budget: <strong className={overBudgetWeeks > 0 ? 'text-red-400' : 'text-emerald-400'}>
          {overBudgetWeeks} weeks
        </strong></span>
        <span>Budget: <strong className="text-emerald-400">20-30 min/day</strong></span>
      </div>

      <div className={hasDetail ? 'h-36 shrink-0' : 'flex-1 min-h-0'}>
        <ResponsiveContainer width="100%" height="100%">
          <BarChart
            data={chartData}
            margin={{ top: 10, right: 20, left: 0, bottom: 5 }}
            onClick={handleBarClick}
            style={{ cursor: 'pointer' }}
          >
            <CartesianGrid strokeDasharray="3 3" stroke="#374151" />
            <XAxis
              dataKey="weekLabel"
              stroke="#9ca3af"
              tick={{ fontSize: 10 }}
              interval={2}
            />
            <YAxis
              stroke="#9ca3af"
              tick={{ fontSize: 10 }}
              label={{
                value: 'min/week',
                angle: -90,
                position: 'insideLeft',
                fontSize: 10,
                fill: '#9ca3af',
                offset: 10,
              }}
            />
            <Tooltip content={<TaskTooltip />} />
            <Legend wrapperStyle={{ fontSize: '10px' }} iconType="square" iconSize={8} />
            <ReferenceLine
              y={BUDGET_HIGH_MIN}
              stroke="#22d3ee"
              strokeDasharray="6 3"
              label={{ value: '30 min/day', fill: '#22d3ee', fontSize: 10, position: 'right' }}
            />
            <ReferenceLine
              y={BUDGET_LOW_MIN}
              stroke="#86efac"
              strokeDasharray="3 3"
              label={{ value: '20 min/day', fill: '#86efac', fontSize: 10, position: 'right' }}
            />
            {activeTypes.map(type => (
              <Bar
                key={type}
                dataKey={type}
                stackId="1"
                fill={TASK_TYPE_COLORS[type] ?? '#6b7280'}
                name={type}
              />
            ))}
          </BarChart>
        </ResponsiveContainer>
      </div>

      {selectedTask && (
        <div className="border-t border-gray-700 pt-3 mt-3 max-h-48 overflow-y-auto">
          <TaskDetail task={selectedTask} onBack={() => setSelectedTask(null)} />
        </div>
      )}

      {selectedRow && !selectedTask && (
        <WeekTaskList row={selectedRow} onSelectTask={setSelectedTask} />
      )}
    </div>
  );
}
